apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    tier: server
    release: stable
    app: nginx
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  keys: |
    user nginx;
     worker_processes  1;
     events {
       worker_connections  10240;
     }
     http {
       server {
           listen       80;
           server_name  _;
           location / {
             root   /usr/share/nginx/html;
             index  index.html index.htm;
         }
       }
     }
