apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    run: api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ingressClassName: ingress-zero
  rules:
    http:
      paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: api-service
              port:
                number: 80
