apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    run: api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    run: api
